### ISSUE TITLE
Albiondata-client closes itself when Albion is running

### ISSUE THREAD

**Issue by NChanard** [ao-data/albiondata-client#82]
All is in title.
I run Albiondata-client then i run my game. When i finaly comme in the game  Albiondata-client closes itself.
I tried to run "D:\Programs\Albion Data Client\albiondata-client.exe" -l "00-00-00-00-00-00" with my physical adress but it return me an error:

![image](https://github.com/ao-data/albiondata-client/assets/55159072/1719f118-ea36-46a5-b1b1-1839fdfdee83)

I

**Comment by phendryx** [comment]
This is likely due to your connection being ipv6, which we don't currently support but need to work on at some point. Seems to be very common for ipv6 if you are using a mobile hotspot.

**Comment by Ymjie** [comment]
INFO[2025-07-19T12:01:33+08:00] Updating player location to DNG-MOR-01-MAIN-029.
INFO[2025-07-19T12:02:28+08:00] Updating player location to 0220.
panic: interface conversion: interface {} is string, not int16

goroutine 8 [running]:
github.com/ao-data/albiondata-client/client.decodeEvent(0x10004f3?)
	/Users/XXX/work/TemporaryFile/albiondata-client/client/decode.go:90 +0xa8
github.com/ao-data/albiondata-client/client.(*listener).onReliableCommand(0x14000083a40, 0x140002a5c58)
	/Users/XXX/work/TemporaryFile/albiondata-client/client/listener.go:253 +0x490
github.com/ao-data/albiondata-client/client.(*listener).processPacket(0x14000083a40, {0x101104430, 0x1400078cf20})
	/Users/XXX/work/TemporaryFile/albiondata-client/client/listener.go:182 +0x6e4
github.com/ao-data/albiondata-client/client.(*listener).run(0x14000083a40)
	/Users/XXX/work/TemporaryFile/albiondata-client/client/listener.go:131 +0xf4
github.com/ao-data/albiondata-client/client.(*listener).startOnline(0x14000083a40, {0x14000010da8, 0x5}, 0x13c0)
	/Users/XXX/work/TemporaryFile/albiondata-client/client/listener.go:54 +0x2b4
created by github.com/ao-data/albiondata-client/client.(*albionProcessWatcher).createListeners in goroutine 1
	/Users/XXX/work/TemporaryFile/albiondata-client/client/albion_watcher.go:69 +0x1a0
