### ISSUE TITLE
client app crashes right after opening it

### ISSUE THREAD

**Issue by eduardylopes** [ao-data/albiondata-client#84]
The application is crashing moments after opening the client, this is happening on the w11 operating system when it has WSL2 installed.

The only alternative to solve this is using the "-l" flag and providing the mac address.

Error: 
```sh
PANI[2024-03-03T16:53:31-03:00] Error opening adapter: O sistema n�o pode encontrar o dispositivo especificado. (20)
panic: (*logrus.Entry) 0xc00038a000

goroutine 38 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000e8000, 0xc0000e5a70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:255 +0x32d
github.com/sirupsen/logrus.(*Entry).Log(0xc0000e80e0, 0x0, 0xc000385f80, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:283 +0xf2
github.com/sirupsen/logrus.(*Entry).Panic(0xc0000e80e0, 0xc000393f80, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:321 +0x5c
github.com/ao-data/albiondata-client/log.Panic(...)
        /home/runner/work/albiondata-client/albiondata-client/log/logger.go:108
github.com/ao-data/albiondata-client/client.(*listener).startOnline(0xc00024e2c0, 0xc00018cdc0, 0x32, 0x13c0)
        /home/runner/work/albiondata-client/albiondata-client/client/listener.go:39 +0xcd
created by github.com/ao-data/albiondata-client/client.(*albionProcessWatcher).createListeners
        /home/runner/work/albiondata-client/albiondata-client/client/albion_watcher.go:69 +0x193
```

**Comment by Icaruk** [comment]
```
INFO[2024-05-01T10:19:29+02:00] Starting Albion Data Client, version: 0.1.36
INFO[2024-05-01T10:19:29+02:00] This is a third-party application and is in no way affiliated with Sandbox Interactive or Albion OnlinERROR systray: systray_windows.go:598 Unable to init instance: Unspecified error [error=Unable to init instance: %v error_location=github.com/getlantern/systray.nativeLoop (systray_windows.go:598) error_text=Unable to init instance: Unspecified error error_type=errors.Error]
ERROR systray: systray_windows.go:598   at github.com/getlantern/systray.nativeLoop (systray_windows.go:598)
ERROR systray: systray_windows.go:598   at github.com/getlantern/systray.Run (systray.go:81)
ERROR systray: systray_windows.go:598   at github.com/ao-data/albiondata-client/systray.Run (systray_win.go:51)
ERROR systray: systray_windows.go:598   at runtime.goexit (asm_amd64.s:1371)
ERROR systray: systray_windows.go:598 Caused by: Unspecified error
e.
INFO[2024-05-01T10:19:29+02:00] Additional parameters can listed by calling this file with the -h parameter.
INFO[2024-05-01T10:19:29+02:00] Watching Albion
```

**Comment by phendryx** [comment]
@Icaruk This is a different issue than the one above. Result is the same but they are caused by different reasons. In your case, the AODP client is booting up to early after your machine restarts and can't put the icon in the system tray (down by the clock). The fix in your case, for now, is just to restart the AODP client manually. At some point in the future, we'll be changing how the AODP client is started on the machine and that error should go away.

**Comment by Icaruk** [comment]
> @Icaruk This is a different issue than the one above. Result is the same but they are caused by different reasons. In your case, the AODP client is booting up to early after your machine restarts and can't put the icon in the system tray (down by the clock). The fix in your case, for now, is just to restart the AODP client manually. At some point in the future, we'll be changing how the AODP client is started on the machine and that error should go away.

Oh sorry, I thought It could be related.

**Comment by phendryx** [comment]
@Icaruk No worries. Most people don't read existing issues and just post a new issue, so it could be worse lol. But as I said, just restarting the client should fix your issue for now. We're working pretty heavily on backend code for the project but this issue (and the OP's issue above) are on the list of things to fix. Just slow going cause it's not a full time job, etc.
